In [ ]:
!git clone https://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@github.com/DiegoAnas/tuw-nlp-contextualized-word-vec.git
%cd tuw-nlp-contextualized-word-vec
!git checkout devD
!git pull
#copy the library to the same directory as this notebook
!cp -r NMT ..

Cloning into 'tuw-nlp-contextualized-word-vec'...
remote: Enumerating objects: 160, done.
remote: Counting objects: 100% (160/160), done.
remote: Compressing objects: 100% (112/112), done.
remote: Total 160 (delta 85), reused 102 (delta 45), pack-reused 0 (from 0)
Receiving objects: 100% (160/160), 68.21 KiB | 563.00 KiB/s, done.
Resolving deltas: 100% (85/85), done.
/content/tuw-nlp-contextualized-word-vec
Branch 'devD' set up to track remote branch 'devD' from 'origin'.
Switched to a new branch 'devD'
Already up to date.


In [ ]:
!pip install datasets
!pip install transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 9.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 8.3 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.


In [ ]:
from __future__ import unicode_literals, print_function, division
from io import open
import unicodedata
import re
import random
import numpy as np

import torch
import torch.nn as nn
from torch import optim
import torch.nn.functional as F
from torch.autograd import Variable
from torch.utils.data import TensorDataset, DataLoader, RandomSampler

from datasets import load_dataset
from transformers import AutoTokenizer

import NMT
from NMT.utils import get_dataloader

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
#training params
num_epochs = 1
batch_size = 64
sentence_length = 40
#learning_rate = 1
#optimizer = "SGD"
#Next options are outdated in favour of optimizer schedulers?
#max_grad_norm
#learning_rate_decay
#start_decay_at

In [ ]:
#TODO change tokenizer tokens (adapt constatns to IDS?)
# bos_token = constants.BOS_WORD, eos_token, unk_token, sep_token, pad_token, cls_token, mask_token
tokenizer_en = AutoTokenizer.from_pretrained('distilbert-base-uncased')
# https://huggingface.co/dbmdz/bert-base-german-cased
tokenizer_de = AutoTokenizer.from_pretrained("dbmdz/bert-base-german-cased")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/59.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/456 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/240k [00:00<?, ?B/s]

In [ ]:
#for num_epoch in num_epochs:
    #input_lang, output_lang, train_dataloader = get_dataloader(batch_size)
#TODO device
train_dataloader = get_dataloader(split="train", input_tokenizer=tokenizer_en,
                                  target_tokenizer=tokenizer_de,
                                  batch_size=batch_size,
                                  sentence_length=sentence_length,
                                  streaming=False,
                                  shard=100)
# 1/100 of dataset = 50k, 20k more than small Dataset
# Medium is 200k
# Large is 7M ~ full dataset is 4,5M

Map:   0%|          | 0/45489 [00:00<?, ? examples/s]

In [ ]:
valid_dataloader = get_dataloaderc(split="validation", input_tokenizer=tokenizer_en,
                                 target_tokenizer=tokenizer_de,
                                 batch_size=batch_size,
                                 sentence_length=sentence_length)

Map:   0%|          | 0/2169 [00:00<?, ? examples/s]

In [ ]:
from NMT import models
#num_layers,
# bidirectional,
# dropout,
#'-rnn_size', default=600,
#'-word_vec_dim', default=400, # ONMT opt.word_vec_size
# dict_size # opt.data -> dict -> dict.size()
#Parameters
rnn_size = 100
word_vec_dim = 50
lstm_layers = 2
dropout = 0.2

encoder = models.Encoder(num_layers=lstm_layers,
                         bidirectional=True,
                         dropout = dropout,
                         rnn_size = rnn_size,
                         word_vec_dim = word_vec_dim,
                         dict_size = len(tokenizer_en),
                         padding = tokenizer_en.convert_tokens_to_ids(tokenizer_en.pad_token))
encoder = encoder.to(device)
decoder = models.Decoder(num_layers=lstm_layers,
                         bidirectional=False,
                         dropout=dropout,
                         rnn_size=rnn_size,
                         word_vec_dim=word_vec_dim,
                         dict_size=len(tokenizer_de),
                         padding = tokenizer_en.convert_tokens_to_ids(tokenizer_en.pad_token))
decoder = decoder.to(device)

In [ ]:
nmtModel = models.NMTModel(encoder,decoder,rnn_size,len(tokenizer_de)).to(device)
nmtModel = nmtModel.to(device)

In [ ]:
del nmtModel, encoder, decoder

In [ ]:
import math
import time
def asMinutes(s):
    m = math.floor(s / 60)
    s -= m * 60
    return '%dm %ds' % (m, s)

def timeSince(since, percent):
    now = time.time()
    s = now - since
    es = s / (percent)
    rs = es - s
    return '%s (- %s)' % (asMinutes(s), asMinutes(rs))

In [ ]:
def train_epochc(dataloader, modelNMT, model_optimizer, criterion, device, print_every:int|None=100):
    total_loss = 0
    start = time.time()
    dataset_size = len(dataloader)
    for batch_num, data in enumerate(dataloader):
        input_tensor, target_tensor = data
        input_tensor = input_tensor.to(device)
        target_tensor = target_tensor.to(device)
        model_optimizer.zero_grad()
        output = modelNMT((input_tensor, target_tensor))
        loss = criterion(output.view(-1, output.shape[-1]), target_tensor.view(-1))
        loss.backward()

        model_optimizer.step()

        total_loss += loss.item()
        if print_every is not None:
            if batch_num % print_every == 0:
                print_loss_avg = total_loss / (batch_num+1)
                print(f"Time {timeSince(start, (batch_num+1) / dataset_size)}, on batch {(batch_num+1)},\
                progress: {(batch_num+1) / dataset_size * 100}%, accumulated loss: {total_loss}, avg loss{print_loss_avg}, last loss: {loss.item()}")

    return total_loss / len(dataloader)

def evaluatec(dataloader, model, criterion, device, print_every:int|None=100)-> float:
    """_summary_

    Args:
        dataloader (_type_): validation / test dataloader
        model (_type_): _description_
        criterion (_type_): _description_
        device (_type_): _description_
        print_every (int | None, optional): _description_. Defaults to 100.

    Returns:
        float: average loss
    """
    total_loss = 0
    start = time.time()
    dataset_size = len(dataloader)
    for batch_num, data in enumerate(dataloader):
        input_tensor, target_tensor = data
        input_tensor = input_tensor.to(device)
        target_tensor = target_tensor.to(device)
        output = model((input_tensor, target_tensor))
        loss = criterion(output.view(-1, output.shape[-1]), target_tensor.view(-1))
        total_loss += loss.item()
        #TODO count correct tokens (?)
        if print_every is not None:
            if batch_num % print_every == 0:
                print_loss_avg = total_loss / (batch_num+1)
                print(f"Time {timeSince(start, (batch_num+1) / dataset_size)}, on batch {(batch_num+1)},\
                progress: {(batch_num+1) / dataset_size * 100}%, accumulated loss: {total_loss}, avg loss{print_loss_avg}, last loss: {loss.item()}")

    return total_loss / len(dataloader)

def trainc(train_dataloader, modelNMT, n_epochs:int,
                valid_dataloader,
                learning_rate:float=0.001,
                print_every:int=100, plot_every:int=100,
                device = torch.device("cuda" if torch.cuda.is_available() else "cpu")):

    start = time.time()
    plot_losses = []
    print_loss_total = 0  # Reset every print_every
    plot_loss_total = 0  # Reset every plot_every

    model_optimizer = optim.Adam(modelNMT.parameters(), lr=learning_rate)
    # TODO make optimizers a parameter for easier set up
    criterion = nn.NLLLoss()
    # TODO look at NLLLoss ignore_index= param for adjusting the weight of token classes like <EOS> etc.

    for epoch in range(1, n_epochs + 1):
        loss = train_epochc(train_dataloader, modelNMT, model_optimizer, criterion, device)
        print_loss_total += loss
        plot_loss_total += loss

        if epoch % print_every == 0:
            print_loss_avg = print_loss_total / print_every
            print_loss_total = 0
            print('%s (%d %d%%) %.4f' % (timeSince(start, epoch / n_epochs),
                                        epoch, epoch / n_epochs * 100, print_loss_avg))

        if epoch % plot_every == 0:
            plot_loss_avg = plot_loss_total / plot_every
            plot_losses.append(plot_loss_avg)
            plot_loss_total = 0

         # evaluate on the validation set
        average_loss = evaluatec(valid_dataloader, modelNMT, criterion, device)
        #valid_ppl = math.exp(min(valid_loss, 100))
        print(f"Validation loss: {average_loss}")
        ### TODO save checkpoints

    #TODO plot?
    #showPlot(plot_losses)

In [ ]:
from NMT.utils import train

trainc(train_dataloader, nmtModel, n_epochs=1, valid_dataloader=valid_dataloader, learning_rate=0.001, print_every=5, plot_every=5, device=device)#learning rate # TODO add other optimizers

nmtModel.eval()

Time 0m 0s (- 60m 47s), on batch 1,                progress: 0.0021983336630833827%, accumulated loss: 10.418479919433594, avg loss10.418479919433594, last loss: 10.418479919433594
Time 0m 9s (- 67m 52s), on batch 101,                progress: 0.22203169997142166%, accumulated loss: 704.4858198165894, avg loss6.9751071268969245, last loss: 7.163918495178223
Time 0m 17s (- 65m 46s), on batch 201,                progress: 0.44186506627975997%, accumulated loss: 1199.411204457283, avg loss5.96721992267305, last loss: 1.3834017515182495
Time 0m 25s (- 62m 38s), on batch 301,                progress: 0.6616984325880982%, accumulated loss: 1800.6478344202042, avg loss5.982218719004001, last loss: 5.739492893218994
Time 0m 33s (- 62m 54s), on batch 401,                progress: 0.8815317988964365%, accumulated loss: 2255.4684846401215, avg loss5.624609687381849, last loss: 1.2665035724639893
Time 0m 43s (- 64m 56s), on batch 501,                progress: 1.101365165204775%, accumulated loss: 

NameError: name 'evaluate' is not defined

In [ ]:
nmtModel.eval()
valid_loss = evaluatec(valid_dataloader, nmtModel, nn.NLLLoss(), device)

Time 0m 0s (- 3m 46s), on batch 1,                progress: 0.04610419548178884%, accumulated loss: 1.3579493761062622, avg loss1.3579493761062622, last loss: 1.3579493761062622
Time 0m 5s (- 1m 43s), on batch 101,                progress: 4.6565237436606735%, accumulated loss: 261.2767754048109, avg loss2.5868987663842664, last loss: 3.8014519214630127
Time 0m 7s (- 1m 9s), on batch 201,                progress: 9.266943291839558%, accumulated loss: 509.08252296224236, avg loss2.532748870458917, last loss: 1.0908852815628052
Time 0m 8s (- 0m 55s), on batch 301,                progress: 13.877362840018442%, accumulated loss: 750.4950652606785, avg loss2.493339087244779, last loss: 3.983659267425537
Time 0m 10s (- 0m 47s), on batch 401,                progress: 18.487782388197328%, accumulated loss: 918.8234113473445, avg loss2.291330202861208, last loss: 1.3806596994400024
Time 0m 12s (- 0m 42s), on batch 501,                progress: 23.09820193637621%, accumulated loss: 1179.58405938

In [ ]:
valid_pairs = next(iter(valid_dataloader))

In [ ]:
print(len(valid_pairs))
print(len(valid_pairs[0]))
print(valid_pairs[0][0])
print(valid_pairs[1][0])

2
64
tensor([ 101, 2634, 1998, 2900, 3539, 7767, 3113, 1999, 5522,  102,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0])
tensor([  102,   229, 15730,  9084, 30886,   136, 27832, 12645,   251,   153,
        16759,   566,   103,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0])


In [ ]:
t_pairs = next(iter(train_dataloader))
print(len(t_pairs))
print(len(t_pairs[0]))
print(t_pairs[0][0])
print(t_pairs[1][0])

2
1
tensor([  101,  2057,  2097,  4876,  8080,  2023, 14651,  3343,  1010,  2029,
         2442,  2022,  2330,  1998, 13079,  1012,   102,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0])
tensor([  102,   505,   338,   687, 16258,  4037,   843,  2376, 11720,   818,
          128,  1872,   136, 16291,   290,  3183,   566,   103,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0])


In [ ]:
from NMT.utils import encode_trans, collate_custom

def get_dataloaderc(split:str, input_tokenizer, target_tokenizer, batch_size:int, sentence_length:int, streaming: bool=False, shard:int|None=None) -> DataLoader:
    """
    Returns the wmt16 dataset.
    params:
    split: str indicates what split of the dataset to return
    > get_dataloader("train")
    """
    #TODO stream is too slow?
    if streaming:
        dataset_origin = load_dataset("wmt16", "de-en", streaming=streaming, split=split, trust_remote_code=True)
    else:
        dataset_origin = load_dataset("wmt16", "de-en", split=split)
        if shard is not None:
            dataset_origin = dataset_origin.shard(shard,1)
    dataset_m = dataset_origin.map(lambda x: encode_trans(x, input_tokenizer, target_tokenizer, sentence_length= sentence_length), remove_columns="translation", batched=True, batch_size=batch_size)
    return DataLoader(dataset_m, collate_fn=collate_custom, batch_size=batch_size)

In [ ]:
input_t = valid_pairs[0].to(device)
tgt_t = valid_pairs[1].to(device)
output_tensor = nmtModel((input_t,tgt_t))

In [ ]:
output_tensor[0].shape

torch.Size([40, 31102])

In [ ]:
_, output_sentence_ids = torch.topk(output_tensor,k=1)
words = tokenizer_de.decode(output_sentence_ids.squeeze(2)[0])

In [ ]:
valid_pairs[0]

tensor([[  101,  2634,  1998,  ...,     0,     0,     0],
        [  101,  2634,  1005,  ...,  3097,  3942,   102],
        [  101,  2720, 16913,  ...,     0,     0,     0],
        ...,
        [  101,  2065,  2035,  ...,     0,     0,     0],
        [  101,  1999,  9177,  ...,     0,     0,     0],
        [  101,  8394, 11616,  ...,     0,     0,     0]])

In [ ]:
 tokenizer_en.decode(valid_pairs[0][0])

'[CLS] india and japan prime ministers meet in tokyo [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]'

In [ ]:
words

'in Die Premierminister Situations und geleistetigt sich in Anliegen. [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]'

In [ ]:
def translate(nmtModel, input, target, target_tokenizer):
    with torch.no_grad():
        output_tensor = nmtModel((input,target))
        #[batch, sentence_length, dict_size]
        output_sentence_ids = torch.topk(output_tensor)
        #TODO check if proper target tokenizer proper words and not sub-word tokens
        # target_tokenizer.decoder = decoders.WordPiece()
        decoded_words = target_tokenizer.decode(output_sentence_ids)

    return decoded_words

def run_evaluation(nmtModel:nn.Module, test_dataloader, input_tokenizer, tgt_tokenizer, print_sentences=False):
    print("Evaluating model on test set:")
    predictions = []
    predictions_tokenized = []
    references = []
    references_tokenized = []
    for input, target in test_dataloader:
        output_words = translate(nmtModel, input, target, tgt_tokenizer)
        #TODO make full sentences for pair references
        references.append(pair[1])
        references_tokenized.append(pair[1].split(" "))
        output_sentence = ' '.join(output_words)
        predictions.append(output_sentence)
        predictions_tokenized.append(output_words)
        if print_sentences:
          print('>', pair[0])
          print('=', pair[1])
          print(f"<{output_sentence}\n")

    bleu = hfeval.load("bleu")
    bleu_score = bleu.compute(predictions=predictions, references=references)
    print("Metric scores:")
    print(f"Corpus BLEU Score on test set: {bleu_score}")
