In [ ]:
!git clone https://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@github.com/DiegoAnas/tuw-nlp-contextualized-word-vec.git
%cd tuw-nlp-contextualized-word-vec
!git checkout devD2
!git pull
#copy the library to the same directory as this notebook
!cp -r NMT ..

fatal: destination path 'tuw-nlp-contextualized-word-vec' already exists and is not an empty directory.
/content/tuw-nlp-contextualized-word-vec
Already on 'devD2'
Your branch is up to date with 'origin/devD2'.
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 12 (delta 6), reused 12 (delta 6), pack-reused 0 (from 0)
Unpacking objects: 100% (12/12), 1.32 KiB | 225.00 KiB/s, done.
From https://github.com/DiegoAnas/tuw-nlp-contextualized-word-vec
   fd67d06..0281ba8  devD2      -> origin/devD2
Updating fd67d06..0281ba8
Fast-forward
 NMT/BCN.py | 23 +++++++++++------------
 1 file changed, 11 insertions(+), 12 deletions(-)


In [ ]:
from __future__ import unicode_literals, print_function, division
from io import open
import unicodedata
import re
import random
import numpy as np

import torch
import torch.nn as nn
from torch import optim
import torch.nn.functional as F
from torch.autograd import Variable
from torch.utils.data import TensorDataset, DataLoader, RandomSampler

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
batch_size = 32
sentence_len = 30
rnn_size = 300
cove = rnn_size
glove = 300
word_vec_dim = glove
glove_cove = glove+cove
bcn_fc_size = 128
maxout_c = 4 #TODO what does this do
dropout = 0.15
target_labels = 2
vocab_size = 50000
params = {"word_vec_size": word_vec_dim,
          "nmt_hidden_size": rnn_size,
          "fc_hidden_size": bcn_fc_size,
          "bilstm_encoder_size": 256,
          "bilstm_integrator_size": 256,
          "maxout_channels": maxout_c,
          "device":"cpu",
          "dropout": dropout}

In [ ]:
!wget https://nlp.stanford.edu/data/glove.6B.zip
!unzip -l ./glove.6B.zip
!unzip -j ./glove.6B.zip glove.6B.300d.txt

--2025-01-29 14:03:49--  https://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2025-01-29 14:03:49--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6B.zip        100%[===================>] 822.24M  5.13MB/s    in 2m 39s  

2025-01-29 14:06:29 (5.16 MB/s) - ‘glove.6B.zip’ saved [862182613/862182613]

Archive:  ./glove.6B.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
171350079  201

In [ ]:
!ls -l

total 1855628
-rw-rw-r-- 1 root root 1037962819 Aug 27  2014 glove.6B.300d.txt
-rw-r--r-- 1 root root  862182613 Oct 25  2015 glove.6B.zip
drwxr-xr-x 3 root root       4096 Jan 29 14:22 NMT
-rw-r--r-- 1 root root        904 Jan 29 14:03 README.md


In [ ]:
!pip install datasets

In [ ]:
from NMT.load_WMT16 import load_tokenizer
tokenizer_path = "./NMT/wmt16_tokenizer.pkl"
tokenizer = load_tokenizer(tokenizer_path)
vocab = tokenizer.word_index

Tokenizer loaded from ./NMT/wmt16_tokenizer.pkl


In [ ]:
from NMT.Data_prep_WMT16 import create_embedding_indexmatrix
glove_embs = create_embedding_indexmatrix("./glove.6B.300d.txt", vocab, vocab_size)

In [ ]:
vocab.items()

dict_items([('<unk>', 1), ('2', 2), ('3', 3)])

In [ ]:
from NMT import models
encoder = models.Encoder(num_layers=2, bidirectional=True,
                         dropout=dropout, rnn_size=rnn_size,
                         word_vec_dim=word_vec_dim, dict_size=vocab_size,
                         vocab=vocab, glove_embeddings= glove_embs)
decoder = models.Decoder(num_layers=2, bidirectional=False, dropout=dropout, rnn_size=rnn_size, word_vec_dim=word_vec_dim, dict_size=vocab_size)
model = models.NMTModel(encoder=encoder, decoder=decoder, rnn_size=rnn_size, tgt_dict_size=vocab_size)

In [ ]:
model.eval()

NMTModel(
  (encoder): Encoder(
    (dropout_l): Dropout(p=0.15, inplace=False)
    (dropout_l2): Dropout(p=0.15, inplace=False)
    (embedding): Embedding(3, 300, padding_idx=0)
    (LSTM): LSTM(300, 150, num_layers=2, batch_first=True, dropout=0.15, bidirectional=True)
  )
  (decoder): Decoder(
    (embedding): Embedding(50000, 300, padding_idx=0)
    (dropout_l1): Dropout(p=0.15, inplace=False)
    (LSTM): LSTM(600, 300, num_layers=2, batch_first=True, dropout=0.15)
    (dropout_l2): Dropout(p=0.15, inplace=False)
    (linear_attn_in): Linear(in_features=300, out_features=300, bias=True)
    (linear_attn_out): Linear(in_features=600, out_features=300, bias=True)
  )
  (linear): Linear(in_features=300, out_features=50000, bias=True)
  (dropout): Dropout(p=0.1, inplace=False)
)

In [ ]:
from NMT.BCN import BCN
classification = BCN(config=params, nmtModel=model, num_labels=2)
classification.eval()

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/rnn.py:123: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.15 and num_layers=1
  warnings.warn(


BCN(
  (encoder): Encoder(
    (dropout_l): Dropout(p=0.15, inplace=False)
    (dropout_l2): Dropout(p=0.15, inplace=False)
    (embedding): Embedding(3, 300, padding_idx=0)
    (LSTM): LSTM(300, 150, num_layers=2, batch_first=True, dropout=0.15, bidirectional=True)
  )
  (fc): Linear(in_features=600, out_features=128, bias=True)
  (bilstm_encoder): LSTM(128, 128, batch_first=True, dropout=0.15, bidirectional=True)
  (bilstm_integrator): LSTM(768, 128, batch_first=True, dropout=0.15, bidirectional=True)
  (attentive_pooling_proj): Linear(in_features=256, out_features=1, bias=True)
  (dropout_pool): Dropout(p=0.15, inplace=False)
  (bn1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (maxout1): Maxout(
    (fc): Linear(in_features=1024, out_features=1024, bias=True)
  )
  (dropout_m1): Dropout(p=0.15, inplace=False)
  (maxout2): Maxout(
    (fc): Linear(in_features=256, out_features=256, bias=True)
  )
  (bn2): BatchNorm1d(256, eps=1e-05, momentum=0

In [ ]:
rand_sentence = torch.randint(0, 2, [sentence_len])
rand_classification_l, class_probs = classification(rand_sentence)

In [ ]:
class_probs

tensor([[0.4749, 0.5251]], grad_fn=<SoftmaxBackward0>)

In [ ]:
for name, param in classification.named_parameters():
  print(name, param.size())

encoder.embedding.weight torch.Size([3, 300])
encoder.LSTM.weight_ih_l0 torch.Size([600, 300])
encoder.LSTM.weight_hh_l0 torch.Size([600, 150])
encoder.LSTM.bias_ih_l0 torch.Size([600])
encoder.LSTM.bias_hh_l0 torch.Size([600])
encoder.LSTM.weight_ih_l0_reverse torch.Size([600, 300])
encoder.LSTM.weight_hh_l0_reverse torch.Size([600, 150])
encoder.LSTM.bias_ih_l0_reverse torch.Size([600])
encoder.LSTM.bias_hh_l0_reverse torch.Size([600])
encoder.LSTM.weight_ih_l1 torch.Size([600, 300])
encoder.LSTM.weight_hh_l1 torch.Size([600, 150])
encoder.LSTM.bias_ih_l1 torch.Size([600])
encoder.LSTM.bias_hh_l1 torch.Size([600])
encoder.LSTM.weight_ih_l1_reverse torch.Size([600, 300])
encoder.LSTM.weight_hh_l1_reverse torch.Size([600, 150])
encoder.LSTM.bias_ih_l1_reverse torch.Size([600])
encoder.LSTM.bias_hh_l1_reverse torch.Size([600])
fc.weight torch.Size([128, 600])
fc.bias torch.Size([128])
bilstm_encoder.weight_ih_l0 torch.Size([512, 128])
bilstm_encoder.weight_hh_l0 torch.Size([512, 128])
b

In [ ]:
input = torch.rand([batch_size, sentence_len, glove_cove])

In [ ]:
rand_sentence = torch.randint(0, 2, [sentence_len])

In [ ]:
del classification
classification = BCN2(config=params, nmtModel=model, num_labels=2)
classification.eval()

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/rnn.py:123: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.15 and num_layers=1
  warnings.warn(


BCN2(
  (encoder): Encoder(
    (dropout_l): Dropout(p=0.15, inplace=False)
    (dropout_l2): Dropout(p=0.15, inplace=False)
    (embedding): Embedding(3, 300, padding_idx=0)
    (LSTM): LSTM(300, 150, num_layers=2, batch_first=True, dropout=0.15, bidirectional=True)
  )
  (fc): Linear(in_features=600, out_features=128, bias=True)
  (bilstm_encoder): LSTM(128, 128, batch_first=True, dropout=0.15, bidirectional=True)
  (bilstm_integrator): LSTM(768, 128, batch_first=True, dropout=0.15, bidirectional=True)
  (attentive_pooling_proj): Linear(in_features=256, out_features=1, bias=True)
  (dropout_pool): Dropout(p=0.15, inplace=False)
  (bn1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (maxout1): Maxout(
    (fc): Linear(in_features=1024, out_features=1024, bias=True)
  )
  (dropout_m1): Dropout(p=0.15, inplace=False)
  (maxout2): Maxout(
    (fc): Linear(in_features=256, out_features=256, bias=True)
  )
  (bn2): BatchNorm1d(256, eps=1e-05, momentum=

In [ ]:
rand_classification_l, class_prob = classification(rand_sentence)

input_sentences dim torch.Size([30])
input_sentences reshaped torch.Size([1, 30])
input type torch.int64
padmask type torch.uint8
input type torch.int64
padmask type torch.uint8
input type torch.int64
padmask type torch.uint8
self_attentive logits dim torch.Size([1, 30])
self_attentive logits post sm torch.Size([1, 30])


In [ ]:
rand_classification

tensor([[-0.1356, -0.0605]], grad_fn=<AddmmBackward0>)

In [ ]:
class_prob

tensor([[0.4799, 0.5201]], grad_fn=<SoftmaxBackward0>)

In [ ]:
rand_classification # with no detach

tensor([[-0.0892,  0.0429]], grad_fn=<AddmmBackward0>)